function mono = makeMonotonous(a)
%MAKEMONOTONOUS Return a logical index of strictly decreasing elements (from the end).
%
%   mono = makeMonotonous(a)
%
%   Given a time vector a that may contain repeated or non-monotone values
%   (e.g. from concatenated ODE segments), returns a logical array of the
%   same length as a such that a(mono) is strictly increasing.
%
%   The algorithm reverses a, keeps track of a running minimum, then
%   reverses the result back so that the *latest* occurrence of each value
%   is preferred (consistent with concatenated simulation chunks where the
%   tail of one chunk may overlap the head of the next).
%
%   Example:
%       t = [0 1 2 2 3];
%       mono = makeMonotonous(t);
%       t(mono)   % [0 1 2 3]
%
%   Generated by GPT, integrated into RunBakersExp refactor.

    % Reverse the array
    arev = flip(a);

    % Find the longest monotonically increasing subsequence from the right
    max_value = arev(1);
    keep_rev = false(size(arev));
    keep_rev(1) = true;

    for i = 2:length(arev)
        if arev(i) < max_value
            keep_rev(i) = true;
            max_value = arev(i);
        end
    end

    % Reverse the logical array to match the original indexing
    mono = flip(keep_rev);
end
