% simplest 
clear;
saveResults = false;
figure(2);
clf; 
% initialize parameters
params0 = getParams();
ModelParamsInitDanOptim_All;

params0.UseOverlapFactor = false;
RunBakersExp;
%%

% rates
a = 1/3;
b = a;

% load modified parameters - any file generated by 
% ModelParamsInit;   
% ModelOptParamsIterDanLoves
ModelParamsInit2;
ModelParamsInitDanOptim3;
params0.MaxSlackNegativeForce = 0;
% already in ModelParamsInit, but free to overwrite any parameter here
params0.alpha0 = 1.5*25*1;
params0.alpha1 = 80;
% params0.alpha2 = 31.5061; 
% params0.alpha3 = 0;
% params0.alphaRip = 100; %
% params0.dr0 = 0;
% params0.dr1 = 0;
% params0.dr2 = -0.005;
% params0.dr3 = -0.01; %
% params0.gamma = 3.61385;
params0.k1 = 1.7*90; % ratchet rate
params0.k2 = 200; % detach rate
% params0.k_2 = 2.79*b;
params0.k2rip = 0; %

params0.ka = 25; % attach rate
params0.kd = 0.30*4*1.00;
params0.kah = 80;
% params0.kadh = 0;
params0.kSE = 10000;
params0.mu  = 0.001;
% params0.kstiff2 = 27373.9;
params0.dr = 0.02;
params0.kstiff1 = 0.55*1.5e4;
params0.kstiff2 = 0.55*1.5e4;
params0.k_pas = 50;
params0.gamma = 3;

params0.ksr0 = 1.7; % transition out of to SRX
params0.sigma1 = 20;
params0.kmsr = 50; % transition in to SRX
params0.sigma2 = 999999;
% params0.UseTitinInterpolation = false;
params0.alpha2_L = 1/0.038;
params0.k2_R = 3e3;
params0.k2_L = 200;
params0.k2 = 1.25*20;
params0.dr2_R = 0.002;
params0.alpha2_R = 1;
params0.RunForceVelocity = 0;
params0.RunSlack = 1;
params0.RunStairs = 0;
params0.RunForceVelocityTime = 0;
params0.dS = 0.004; % set the space resolution
% params0.gamma = 1;
% params0.k_pas = 10;
ModelParamsInitDanOptim2;
% params0.ksrm = 0;
params0.ksr0 = 1e3;
params0.sigma1 = 1e6;
params0.kstiff1 = 18e3;
params0.kstiff2 = params0.kstiff1;
params0.dr = 0.01;
params0.alpha2_L = 50;
params0.kSE = 100;
params0.ML = 2.0;
% params0.MaxSlackNegativeForce = -5;
params0.justPlotStateTransitionsFlag = false;



%% initialize parameters from scratch
clear;
figure(80085);
clf;
params0 = getParams();
% ModelParamsInitNiceSlack;
% ModelParamsInitOptim_slack4;
% ModelParamsInit_slack1;
ModelParamsOptim_tmp;

params0.PlotEachSeparately = true;
params0.ShowStatePlots = true;

params0.UseOverlap = true;
params0.justPlotStateTransitionsFlag = false;
params0.ShowStatePlots = false;
params0.UseDirectSRXTransition = false;
% params0.ghostLoad = 'NiceFit_Compliant';
% params0.ghostSave = 'NiceFit_slack4';

params0.RunSlackSegments = 'Last';
params0.e2L = 1;
params0.dr1 = 0.1;
params0.alpha1 = 23;
params0.k1 = 1;

params0.alpha2_L = -200;
params0.k2 = 20;
params0.dr2 = 0.002;
params0.alpha2_R = 3000;
params0.e2R = .25;




LoadData; 
tic
RunBakersExp;
toc
xl = xlim();
%% 
figure(3); clf;
rates = [out.RTD; out.RD1; out.R1D; out.R12; out.R21; out.XB_Ripped; out.RSR2PT; out.RPT2SR; out.XB_TORs];
lgs = {'RTD', 'RD1', 'R1D', 'R12', 'R21', 'XB_{Ripped}', 'SR2PT', 'PT2SR', 'A2 dett'}
ints = [1 2 7 8 9]

plot(out.t, rates(ints, :), 'LineWidth',2);
xlim(xl)
legend(lgs(ints))

%% save pic
saveas(figure(2), 'slack.png')
figure(1); plot(out.t,out.FXBPassive)
figure(3); plot(out.t,out.p2_1./out.p2_0)
out.XB_TORs(end)

%% Store the results
if ~saveResults
    return
end
%% store the results
modNames = getAllDifferent(params0);
writeParamsToMFile('ModelParamsInit_TF2_slack4.m', params0, modNames);

%% fit the slack

plotData = true;

t = out.t; SL = out.SL; Force = out.Force;
tic
costSlackOnset = fitSlackForceOnset(datatable, velocitytable, t, SL, Force, plotData);
toc

%% Show the transition rates
figure(3); clf;
rates = [out.RTD; out.RD1; out.R1D; out.R12; out.R21; out.XB_Ripped; out.RSR2PT; out.RPT2SR; out.XB_TORs];
lgs = {'RTD', 'RD1', 'R1D', 'R12', 'R21', 'XB_{Ripped}', 'SR2PT', 'PT2SR', 'A2 dett'}
ints = [1 2 7 8 9]

plot(out.t, rates(ints, :), 'LineWidth',2);
legend(lgs(ints))

%% calculate ML at 2.0 um SL
params = params0;
% params.ka = 0;
params.ML = 2.0;
% params.kSE = 100;

    params.Velocity = 0;

    params.SL0 = 2.1;
    rsl0 = params.SL0 / 2.0
    params.Slim_l = 1.85;
    params.Vums = 0;
    % params.Slim_r = 2.2;
    % params.LXBpivot = 2.2;
    % params.dS = 0.0025;
    
if isfield(params, 'PU0')
    params = rmfield(params, 'PU0');
end

% reset the PU0
params = getParams(params, params.g, true);
    
% [F out] = evaluateModel(modelFcn, velocitytable(:, 1), params);
[F out] = evaluateModel(@dPUdTCaSimpleAlternative2State, [0 1], params);

figure(1);clf;
nexttile; plot(out.t, out.SL, out.t, out.LXB); legend('ML', 'SL');
nexttile; plot(out.t, out.Force, out.t, out.FXB); legend('Total force', 'active only');
