% simplest 
clear;
saveResults = false;
figure(2);clf; 
% initialize parameters
params0 = getParams();

% load modified parameters - any file generated by 
% ModelParamsInit;   
% ModelOptParamsIterDanLoves
ModelParamsInit;

% already in ModelParamsInit, but free to overwrite any parameter here
% params0.alpha1 = 0;
% params0.alpha2 = 31.5061;
% params0.alpha3 = 0;
% params0.alphaRip = 0; %
% params0.dr1 = 0;
% params0.dr2 = 0.005;
% params0.dr3 = 0; %
% params0.gamma = 3.61385;
% params0.k1 = 1077.29;
% params0.k2 = 396.747;
% params0.k2rip = 0; %
% params0.ka = 549.243;
% params0.kadh = 0;
% params0.kah = 119.268;
% params0.kd = 170.854;
% params0.kmsr = 955.649;
% params0.kSE = 10000;
% params0.ksr0 = 16.1169;
% params0.kstiff1 = params0.kstiff2;
% params0.kstiff2 = 27373.9;
% params0.k_pas = 115.647;
% params0.sigma1 = 100;
% params0.sigma2 = 0.0413337;

LoadData;
RunBakersExp;


%% Store the results
if ~saveResults
    return
end
%% store the results
modNames = getAllDifferent(params0);
writeParamsToMFile('ModelParamsInit.m', params0, modNames);
