% simplest 
clear;
saveResults = false;
figure(2);clf; 
% initialize parameters
params0 = getParams();

% rates
a = 1/3;
b = a;

% load modified parameters - any file generated by 
% ModelParamsInit;   
% ModelOptParamsIterDanLoves
ModelParamsInit;
params0.MaxSlackNegativeForce = -2;
% already in ModelParamsInit, but free to overwrite any parameter here
params0.alpha1 = 30;
params0.alpha2 = 31.5061;
% params0.alpha3 = 0;
params0.alphaRip = 100; %
% params0.dr1 = 0;
params0.dr2 = -0.005;
params0.dr3 = -0.01; %
% params0.gamma = 3.61385;
params0.k1 = 1077.29*b;
params0.k2 = 396.747*b;
params0.k_2 = 2.79*b;
params0.k2rip = 200; %

params0.ka = 549.243*a;
params0.kd = 170.854*a;
params0.kah = 119.268*a;
% params0.kadh = 0;
params0.kmsr = 800.649;
% params0.kSE = 10000;
params0.ksr0 = 20.1169;
params0.kstiff2 = 27373.9;
params0.kstiff1 = params0.kstiff2;
% params0.kstiff2 = 27373.9;
% params0.k_pas = 115.647;
% params0.sigma1 = 100;
% params0.sigma2 = 0.0413337;
params0.UseTitinInterpolation = false;

LoadData;
RunBakersExp;

%% Store the results
if ~saveResults
    return
end
%% store the results
modNames = getAllDifferent(params0);
writeParamsToMFile('ModelParamsInit2.m', params0, modNames);
