clear;
figure(2);
clf; 
% initialize parameters
params0 = getParams();

% new modifiers - to be overwritten
params0.justPlotStateTransitionsFlag = false;
params0.RunForceVelocityTime = false;
ModelParamsInitDanOptim3;

% load modified parameters - any file generated by 

% ModelParams; % awful, no way
% ModelParamsInit % same old
% ModelOptParams % featuring double peaks
% ModelOptParamsIter % damped first peak
% ModelOptParamsAllgood % messed up
% ModelOptParamsIterDanLoves % unstable

% ModelParamsInitDan % nice last slack-restretch, force in the ballpark
% ModelParamsInitDanOptim % same
ModelParamsInitDanOptim2 % same but better
% ModelParamsInitDanOptim3 % same but plots all stuff 

% params0.kSE = 1000

params0.justPlotStateTransitionsFlag = false;

rsl0 = 1.0025;
rsl0 = 1.0650;
params0.SL0 = 2.2*rsl0;

LoadData; 
tic
RunBakersExp;
toc